### ISSUE TITLE
manifest.yml file missing for theme installation

### ISSUE THREAD

**Issue by doque** [johnotander/pixyll#100]
Using a vanilla copy of JekyllBootstrap, I tried installing the Pixyll Theme:

    rake theme:install git="git@github.com:johnotander/pixyll.git"
	Cloning into './_theme_packages/_tmp'...
	remote: Counting objects: 998, done.
	remote: Total 998 (delta 0), reused 0 (delta 0)
	Receiving objects: 100% (998/998), 892.24 KiB | 237.00 KiB/s, done.
	Resolving deltas: 100% (574/574), done.
	Checking connectivity... done.
	rake aborted!
	No such file or directory - ./_theme_packages/_tmp/manifest.yml
	/Users/dbusser/Apps/doque.github.com/Rakefile:289:in `initialize'
	/Users/dbusser/Apps/doque.github.com/Rakefile:289:in `open'
	/Users/dbusser/Apps/doque.github.com/Rakefile:289:in `verify_manifest'
	/Users/dbusser/Apps/doque.github.com/Rakefile:270:in `theme_from_git_url'
	/Users/dbusser/Apps/doque.github.com/Rakefile:171:in `block (2 levels) in <top (required)>'
	Tasks: TOP => theme:install
	(See full trace by running task with --trace)

It seems there must be a manifest.yml file in order to install this theme?

**Comment by johnotander** [comment]
Yeah, absolutely @doque . I will be adding the functionality for #99 in the next few days.
