### ISSUE TITLE
Customization of width and font sizes

### ISSUE THREAD

**Issue by rassol** [johnotander/pixyll#101]
Is it possible to add the possibility to set a custom width in _config.yml? 
Same question for the font size.

Would like the with a little wider and the fonts a little smaller. Or do you have to do it in css?

Thanks!

**Comment by rassol** [comment]
@johnotander yes I would say it's in line with what I was thinking. 

I guess the problem then would be what variables to include. Probably more and more vars will be added gradually over time. I am currently overriding the padding of blockquotes, I do not suspect that var will be added initially.

There are widths and heights, font sizes, colors, padding and margins etc. Could get messy using sass vars too, but certainly better than the current way.

Maybe there's a way to structure and scope the vars. For example, `global`, `post`, `page` scopes.

But ideally the default styles should be pretty good enough and best practice and the need for customization small.

**Comment by johnotander** [comment]
Ideally, the majority of commonly customized aspects will be introduced as variables. You can keep an eye on the current CSS refactoring branch I'm working out of if you like: <https://github.com/johnotander/pixyll/tree/revamp-css>. This will give somewhat of an illustration of which variables will be configurable when it's ready for merging.

**Comment by TimothyGu** [comment]
Beautiful! Keep up with the great work!

**Comment by johnotander** [comment]
Thanks, @TimothyGu ! Should be ready to roll in the next week or so. : )

**Comment by johnotander** [comment]
Closing this issue since I've created a PR with the current work in progress #120. Feel free to continue the discussion there! Once complete it will have variables to change the font and widths of the page.
