### ISSUE TITLE
Improve formatting of line numbers in syntax highlighting

### ISSUE THREAD

**Issue by datalove** [johnotander/pixyll#117]
Hi John - loving your theme! There is one minor thing I'd like to see different though. 

Can we make the default formatting for the line numbers in syntax highlighting less salient?

Also, it would be great if the code could be selected without including the line numbers in the selection.

Something like what's referred to in the link below would be great for example (I tried to get it working in pixyll but am too unfamiliar with CSS).

https://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html

**Comment by johnotander** [comment]
Hey @datalove, I'm glad your loving it!

Yeah, I haven't really looked into the line number formatting at all, but I will do so later this week. Thanks for including the relevant link, it looks like it should be pretty straightforward for me to improve code snippet line numbering.

**Comment by datalove** [comment]
Great news @johnotander! I have done a bit more digging and found another link that might be relevant.

http://drewsilcock.co.uk/proper-linenumbers/

Cheers

**Comment by johnotander** [comment]
This is awesome! Thank you.

**Comment by johnotander** [comment]
Hey @datalove,

I'm getting close to getting the latest release out, which includes a massive CSS rewrite and includes line numbers (which aren't user selectable) for code blocks. Here's a teaser:

![sht238qg7qkbjxwv5evmqoawdaijbovektvhqw6n6am](https://cloud.githubusercontent.com/assets/1424573/6130681/eb6a1748-b103-11e4-96a2-62da51b809f3.png)

**Comment by datalove** [comment]
That looks beautiful! Can't wait to pull it.

**Comment by johnotander** [comment]
This should be included in the v2.0 release.
