### ISSUE TITLE
Add google analytics info to the readme

### ISSUE THREAD

**Issue by johnotander** [johnotander/pixyll#118]

**Comment by bartekpl** [comment]
What kind of info do you need? Happy to help.

**Comment by johnotander** [comment]
:sunglasses: 

Really just a one line blurb that mentions the fact it can be configured via the `_config.yml`.

**Comment by bartekpl** [comment]
Oh, then I think it's done with #270 - I've added GA info there.

**Comment by johnotander** [comment]
Ah, yep. You are correct. Thanks again : )
