### ISSUE TITLE
Incorporate social sharing to the bottom of posts

### ISSUE THREAD

**Issue by johnotander** [johnotander/pixyll#119]

**Comment by shrutirij** [comment]
Hi,

First off, thanks for Pixyll!

I'm using it on my blog and I've incorporated (rather basic) social sharing. Example post [here](http://shrutirijhwani.com/2015/03/07/hello-world/). 

If it's suitable, I can create a pull request and contribute :)

**Comment by johnotander** [comment]
Hey @shrutirij,

That looks perfect! I'd gladly accept a PR for your implementation. Along the same lines as the `show_social_icons` key in the config, it'd be great to have a`show_sharing_icons` key.

Thanks!
