### ISSUE TITLE
Visible scroll, by design?

### ISSUE THREAD

**Issue by rassol** [johnotander/pixyll#123]
If a page isn't filled with content, there is always a bottom margin at the footer, is this by design?
Seems that the more rows of text in the footer the more you can scroll.

**Comment by johnotander** [comment]
This is a CSS bug, I will be addressing it in #120 as part of the CSS revamp.

**Comment by rassol** [comment]
Ah ok. Thanks.
I haven't checked out the CSS revamp yet.

**Comment by johnotander** [comment]
Thanks for reporting :)
