### ISSUE TITLE
Embed Responsively Youtube video

### ISSUE THREAD

**Issue by marste** [johnotander/pixyll#125]
Tip: http://avexdesigns.com/responsive-youtube-embed/

**Comment by marste** [comment]
I added in _main.scss:

.video-responsive{
    overflow:hidden;
    padding-bottom:56.25%;
    position:relative;
    height:0;
}
.video-responsive iframe{
    left:0;
    top:0;
    height:100%;
    width:100%;
    position:absolute;
}

When add a youtube video I use class "video-responsive":

<div class="video-responsive">
    <iframe width="560" height="315" src="//www.youtube.com/embed/LP66TJwvqaU" frameborder="0" allowfullscreen></iframe>
</div>

**Comment by johnotander** [comment]
The CSS in v2.0 should ensure that the iframe is now responsive.
