### ISSUE TITLE
There's no "thanks.html"

### ISSUE THREAD

**Issue by kristiannordestgaard** [johnotander/pixyll#132]
Hi John,

Two minor comments regarding the contact form:

1) There's no thanks.html, leading to a 404 after submitting. Not a biggie as it's pretty easy to make one, but you might want to know.

2) The info in readme.md is out of date as the contact script uses the email from _config.yml now.

PS: Thanks a bunch for making this theme, it really spices up my site. 

Best, 
Kristian

**Comment by johnotander** [comment]
Thanks for creating this issue, @kristiannordestgaard, these are great points! I'll work on addressing both these issues shortly.

**Comment by johnotander** [comment]
This was addressed a while back, forgot to close the issue :blush:
