### ISSUE TITLE
Redesign Code Blocks

### ISSUE THREAD

**Issue by nahtnam** [johnotander/pixyll#137]
Hey!

I just wanted to say that in my opinion the code blocks dont match pixyll's minimalistic design. I think something like githubs design would look better.

```
This is githubs design
```

**Comment by johnotander** [comment]
Hey @nahtnam,

I 100% agree, I'm hoping to incorporate a new code design based off of Basscss [[example](http://www.basscss.com/docs/guides/ui/#button-sizes)]. It is similar to Github's design, but with a touch more "pop". Also, Pixyll uses a lot of the Basscss CSS to begin with. Though, I suspect I will be toning down the syntax highlighting a bit.

**Comment by nahtnam** [comment]
Sounds good. The only thing that bothers me is that the sideways scroll bar shows up even though its disabled.

Personally I like github syntax highlighting. Its light and easy to read. https://github.com/github/linguist

**Comment by johnotander** [comment]
Ah, yeah. The scrollbar will be hidden if there is nothing to scroll horizontally.

**Comment by nahtnam** [comment]
Any updates?

**Comment by johnotander** [comment]
Been making some progress on the new version of Pixyll. What I've got so far looks like:

![sht238qg7qkbjxwv5evmqoawdaijbovektvhqw6n6am](https://cloud.githubusercontent.com/assets/1424573/6130681/eb6a1748-b103-11e4-96a2-62da51b809f3.png)

I've been hoping to push out this update for a while, but I've been pretty busy with work. If all goes well I'll have more time next weekend to make more significant progress.

**Comment by nahtnam** [comment]
Looks beautiful. Thanks for the update?

**Comment by nahtnam** [comment]
!

**Comment by johnotander** [comment]
This should be fixed in v2.0.
