### ISSUE TITLE
Multiple Authors

### ISSUE THREAD

**Issue by nahtnam** [johnotander/pixyll#138]
Hey!

Is there/will there be multiple authors support?

**Comment by nahtnam** [comment]
Sorry, this way already solved, but I want to rephrase my question:

Will there be an about the author page, or do we have to create a page like this: http://pixyll.com/about/

**Comment by johnotander** [comment]
No worries! At this point the `about.md` is intended to be the author page. Is there something you think that's missing?

**Comment by nahtnam** [comment]
Nothing specific really. If im not wrong, the url is different, but i dont think it matters.
