### ISSUE TITLE
InstantClick integration

### ISSUE THREAD

**Issue by nahtnam** [johnotander/pixyll#139]
Suggestion:

Add http://instantclick.io/ to make pages load faster, and make browsing seamless.

**Comment by johnotander** [comment]
Thanks for the suggestion. I'll experiment with instant click sometime soon to see if it will be a good fit/accessible/performant.

**Comment by nahtnam** [comment]
Kk. It would be really cool if it could be implemented.

**Comment by johnotander** [comment]
We can leave it open to remind me to look into it : ) later this week or next week.

**Comment by johnotander** [comment]
In attempt to keep Pixyll as vanilla Jekyll as possible, I won't be adding this functionality. Though, thanks for creating this issue to discuss this!

**Comment by tgaeta** [comment]
A little late to the party, but there is absolutely no need for that.

![screen shot 2015-09-01 at 10 32 51 pm](https://cloud.githubusercontent.com/assets/9040988/9647915/487baf08-51b0-11e5-89d2-904e14069765.png)

To achieve a very fast site, just follow this blog by [jdsteinbach](https://github.com/jdsteinbach) on [Achieving a 99/100](https://jdsteinbach.com/performance/99-100-google-page-speed/) on Google's [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/). 

When you do this, and then introduce InstantClick, the results will be marginal. My Jekyll blog, which is using the Pixyll theme during the speed test (100/100 mobile, 100/100 desktop), is faster than ever... it'd be almost impossible for me to discern the difference in speed with InstantClick. That doesn't mean InstantClick doesn't have a need or place; however, if @johnotander wants _"to keep Pixyll as vanilla Jekyll as possible"_ yet address the speed of the theme, then I'd recommend he investigate the blog above.
