### ISSUE TITLE
Social links are not shown in Chrome

### ISSUE THREAD

**Issue by anissen** [johnotander/pixyll#143]
Here's a comparison of my blog in Chrome (top) and Safari (bottom):

![screen shot 2015-03-03 at 20 41 10](https://cloud.githubusercontent.com/assets/879967/6470695/d0200cc0-c1e5-11e4-861d-3886532ea503.png)

The links are shown in FireFox as well. I'm using the latest version of pixyll from the `gh-pages`-branch but I've seen the same behavior on the `revamp-css`-branch.

**Comment by johnotander** [comment]
Thanks for reporting this.

Are you running the same site locally as what's located here?: http://andersnissen.com/blog/ As I'm able to see the icons with the latest Chrome there.

**Comment by anissen** [comment]
You are absolutely right. Apparently it's my ublock (https://github.com/gorhill/uBlock) Chrome extension that's blocking the social icons. Too aggressively I'd say, but it's not pixyll's fault.

Thanks for this beautiful theme. Keep up the good work :+1:

**Comment by johnotander** [comment]
Glad it's resolved! :)
