### ISSUE TITLE
Doesn't work if not named Index.html

### ISSUE THREAD

**Issue by Vitallity** [johnotander/pixyll#144]
I am set on this theme, but it causes issues when added to an existing site. If the index.html is named anything other than index.html, for example blog.html it would display a 404 error where the posts should be. I nailed this down after fiddling with directories and the config file, just renamed it to index.html and it worked. I do not have the Jekyll knowledge to track down and fix this issue that's why I'm submitting this here.

**Comment by johnotander** [comment]
Thanks for reporting this, @Vitallity. I'll do a little digging to see what's going on.

**Comment by johnotander** [comment]
Looks like this is an issue with Jekyll itself rather than Pixyll.
