### ISSUE TITLE
Code blocks have scrollbar

### ISSUE THREAD

**Issue by nahtnam** [johnotander/pixyll#147]
Hey!

I remember we talked about this in another issues. Basically the side scrollbar is showing for no reason: http://i.imgur.com/pH5mJY7.png

Just a reminder!

**Comment by nahtnam** [comment]
@johnotander @changetip $1 Keep up the amazing work! :)

**Comment by changetip** [comment]
Hi @johnotander, @nahtnam sent you a Bitcoin tip worth 3,539 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/645056)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by johnotander** [comment]
Thanks, @nahtnam ! I will get digging in to it this weekend.

**Comment by nahtnam** [comment]
@johnotander 0.00476BTC @changetip 

*This is the leftovers. Bitcoin volatility

**Comment by nahtnam** [comment]
@johnotander 0.00476 BTC @changetip

*This is the leftovers. Bitcoin volatility

**Comment by changetip** [comment]
Hi @johnotander, @nahtnam sent you a Bitcoin tip worth 0.00476 BTC ($1.25), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/653962)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by johnotander** [comment]
Change Tip is pretty cool. Thanks @nahtnam I appreciate the tip. I'll let you know when I get the code blocks fixed. :beers:

**Comment by nahtnam** [comment]
Awesome.

**Comment by johnotander** [comment]
This should be fixed in v2.0 of Pixyll.
