### ISSUE TITLE
Issue when a link in the preview text.

### ISSUE THREAD

**Issue by acamps** [johnotander/pixyll#148]
If you have a **link** in the short text that appears for every article at the home, the _text before_ the link appears blue too.

**Comment by johnotander** [comment]
Hm, that's quite weird. I will have a look this weekend. Thanks for reporting!

**Comment by acamps** [comment]
If I can provide any help I will be happy to!

**Comment by acamps** [comment]
Obviously thought not a nice solution, adding this in the `sass` files, tricks the eye.
```css
.post-link {
    color: #000000;
}
```
However, the link stays.

I have also tried with the 
```liquid
{% post.excerpt %}
```
replacing `post.summary` variable in the `index.html`, but the result is exactly the same.

It looks more like a *jekyll issue* than a Pixyll issue.

**Comment by psicomante** [comment]
I propose this change #154.

btw, great project!!

**Comment by johnotander** [comment]
Thanks for the help getting this resolved @acamps and @psicomante !
