### ISSUE TITLE
Disqus page.id

### ISSUE THREAD

**Issue by acamps** [johnotander/pixyll#150]
When I was use the default implementation for **disqus**, the generated discussion points to localhost:4000

**Maybe there's something at `_config.yml` I'm missing**, but what worked for me was to remove the variable `disqus_identifier` from the template. Then it gets the url form window.href.url - I think-, and it works ok.

**Comment by acamps** [comment]
If you want to try my huge contribution :laughing:

**Comment by johnotander** [comment]
Thanks for diving in here, @acamps!

I actually don't use disqus, so I'm not familiar with how it all works, however, it appears that the [disqus_identifier](https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables#disqus_identifier) is used to uniquely identify a page. This ensures that each post has a unique discussion thread. So, it appears as though it should remain as part of the disqus script.

Though, why you were seeing the strange behavior with the discussion pointing to `localhost:4000`, I have no idea what's going on there. I wonder if anyone else has seen such behavior. I will have time tomorrow to dive into this a little deeper and see what's going on.

**Comment by fernandomantoan** [comment]
It happened to me too, but I don't think that removing the `disqus_identifier` is the way to go... I think that defining it is a good practice... In my case, Disqus duplicated the URLs, generating two discussions and messing with all the comments, but it was simple to solve: I migrated the URLs using the https://help.disqus.com/customer/en/portal/articles/912757-url-mapper, making the `localhost` discussion become the right URL.

**Comment by johnotander** [comment]
Thanks @fernandomantoan! Looks like the documentation linked should solve this issue. 👯

**Comment by alxmjo** [comment]
As a follow-up, I believe the reason you get the Disqus discussions pointing to `localhost` is because you're loading Disqus from a development build (on your local machine, perhaps). You can prevent this behavior if you add in a check for a production environment like so:

```
{% if site.disqus_shortname and page.comments != false and jekyll.environment == "production" %}
  <div id="disqus_thread"></div>
  <script type="text/javascript">
  ...
```
