### ISSUE TITLE
Listing blog posts in a separated 'Blog' page

### ISSUE THREAD

**Issue by eduardocoelho** [johnotander/pixyll#164]
Hi,
First I'd like to thank you for your Jekyll theme, I'm using it on my personal website www.educoelho.com and it works great! Now I'd like to create some blog posts but haven't found out how to show it in a separated 'Blog' page.

I took a look at your sample code and realized that the template works fine when showing the blog posts in the 'index.html' (the website main page). However I'd like to have the index.html showing my personal information and show the blog posts in a 'Blog' page instead (just like the 'Curriculum' or 'Past' in my website).

The steps I've done so far are as follows:
1. Added `<a href="{{ site.baseurl }}/blog/">Blog</a>` to the `_includes/navigation.html`
2. Created a sample blog post in `_posts/2015-05-21-first-blog-post.md` with the following content:
```
---
layout:     post
title:      My first blog post
date:       2015-05-21 15:20:00
summary:    This is an empty post to illustrate the pagination component with Pixyll.
categories: blog post bash
---

This is my first blog post with jekyll.
```

Then, when I rebuild the website I got the following warning message: "Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination."

Could you give me some guidance on that?
Thanks.

**Comment by dwlfrth** [comment]
@eduardocoelho 
You may want to add the following parameter to _config.yml: paginate_path: "blog/page:num"
Also, make sure to adapt _includes/pagination.html accordingly :)

**Comment by eduardocoelho** [comment]
Thanks @dwlfrth, that works now.
Here are the steps I did:

**Comment by eduardocoelho** [comment]
Thanks @dwlfrth, that works now.
I Managed to work by doing the following:

**Comment by eduardocoelho** [comment]
Thanks @dwlfrth, that works now.
I did the following steps:

1. Added `paginate_path: "blog/page:num"` to `_config.yml`
1. Replaced occurrences of `{{ site.baseurl }}/` by `{{ site.baseurl }}/blog/` in `_includes/pagination.html`
1. Created a folder `/blog/` in the site root and moved the sample `index.html` onto `blog/index.html`.

**Comment by dwlfrth** [comment]
@eduardocoelho 
Faced the exact same "issue" a month ago while migrating my stuff to Pixyll ;)
Pleasure!

**Comment by johnotander** [comment]
Thanks @eduardocoelho and @dwlfrth for getting to the bottom of this and documenting your approach to implementing this. I'm sure it will be very useful for others in the future. Thanks! :beers:
