### ISSUE TITLE
Title and header links are horizontally unaligned

### ISSUE THREAD

**Issue by sindresorhus** [johnotander/pixyll#172]
<img width="857" alt="screen shot 2015-07-11 at 01 01 19" src="https://cloud.githubusercontent.com/assets/170270/8630622/6fce596a-2768-11e5-8ef3-7b6e44447fdc.png">

-

Before 2.0.0:

<img width="792" alt="screen shot 2015-07-11 at 01 02 11" src="https://cloud.githubusercontent.com/assets/170270/8630626/7ddbc7d6-2768-11e5-8291-48365b48a6ae.png">

**Comment by johnotander** [comment]
Alignment should be fixed now.
