### ISSUE TITLE
Site title and header links should be larger on smaller screens

### ISSUE THREAD

**Issue by sindresorhus** [johnotander/pixyll#173]
The header links are hard to tap and it would look better if the site title were a bit larger. 

iPhone 6:

<img width="487" alt="screen shot 2015-07-11 at 01 06 54" src="https://cloud.githubusercontent.com/assets/170270/8630748/03b57766-276a-11e5-83d4-7e34842fa886.png">

**Comment by johnotander** [comment]
I bumped the font size up on the nav and just tested on my iPhone 5s. Should be easier to tap now, let me know if you think the links should go up another size.

**Comment by sindresorhus** [comment]
Link size looks good, but I kinda want the site title to be larger and with more top and bottom margin. Currently too similar and too close to the links.

<img width="487" alt="screen shot 2015-07-11 at 02 08 11" src="https://cloud.githubusercontent.com/assets/170270/8631213/ddcb473a-2771-11e5-89e8-85f4bce58c4c.png">

**Comment by johnotander** [comment]
Ah, yeah. I think we can bump the title font size up a scale to make it more apparent. I'll get working on that now, thanks!

**Comment by johnotander** [comment]
Thoughts @sindresorhus ?:

![0vzl1bpnjpzuwi8sp_olc149cpgujidoflmtu8fhvsq](https://cloud.githubusercontent.com/assets/1424573/8659558/fef77f84-2968-11e5-816a-de5ec68a28b0.png)

**Comment by sindresorhus** [comment]
:+1:
