### ISSUE TITLE
Bug with social icons

### ISSUE THREAD

**Issue by maxdel** [johnotander/pixyll#178]
When I display social icons, they locate in the center, not in the left. 
It's because of the following code in the _header.scss:
```javascript
social-icons .left, .social-icons .right {
  text-align: center;
  float: none;
}
```
But deleting this code causes problems with a mobile version of this design.

**Comment by johnotander** [comment]
Thanks for reporting this! I forgot to update the social icon styling in version `2.0.0`. I've got this on my list for tomorrow to push out a fix.

**Comment by MohamedBassem** [comment]
+1

**Comment by MohamedBassem** [comment]
Any updates here ?

**Comment by johnotander** [comment]
This is now fixed in the latest version, `2.5.2`.

**Comment by mbialon** [comment]
Thanks.

**Comment by MohamedBassem** [comment]
Thank you :+1:
