### ISSUE TITLE
Bug: Footer does not stay at the bottom of the window (possibly Safari only)

### ISSUE THREAD

**Issue by Joshfindit** [johnotander/pixyll#182]
When content is shorter than the page, the footer rises to meet the content which leaves white space underneath it.

![screenshot 2015-07-22 12 01 04](https://cloud.githubusercontent.com/assets/1937155/8829548/92c4838c-306d-11e5-97f6-0fd5efda640b.png)

I found a pure-CSS solution here: http://www.cssreset.com/demos/layouts/how-to-keep-footer-at-bottom-of-page-with-css/#

**Comment by Joshfindit** [comment]
Note: It's outside my comfort zone, but if someone confirms that the solution fits with Pixyll I'll work to create a pull request.

**Comment by captbaritone** [comment]
This approach requires hard coding a height for the footer, which may not work with everybody's footer content.

**Comment by tgaeta** [comment]
I was just working on this and decided to see if this was a working an issue.

Safari is the only browser that I've tested (mobile and mac) which does this to the footer. Chrome and Firefox treat the footer as if it where `position: sticky;`

Completely different note: Safari won't accept the `required="true"` for the contact form to provide at least a level of protection from receiving blank contact form submissions. The reason why I'm bringing it up is to demonstrate that Safari isn't playing nicely with this theme.

**Comment by Joshfindit** [comment]
Interestingly enough, I don't see this issue any more on Safari 9.0 (OSX 10.11 beta 6).

**Comment by tgaeta** [comment]
Hmmm.. I'm on `Version 8.0.7 (10600.7.12)`

**Comment by tgaeta** [comment]
Just updated: OSX Yosemite 10.10.5 (14F27) | Safari 8.0.8 (10600.8.9)... still an issue for me.

**Comment by johnotander** [comment]
I believe it's an issue because I currently don't have vendor prefixes for my use of flexbox in the CSS, I'll go ahead and add those in now to see if they fix things.
