### ISSUE TITLE
OSX, Safari: Pixyll jumps around when resized horizontally.

### ISSUE THREAD

**Issue by Joshfindit** [johnotander/pixyll#183]
1. Open http://pixyll.com in Safari (Chrome seems unaffected)
2. Slowly resize the window horizontally.

Result:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1937155/8834117/d10df626-3088-11e5-94bc-3859f826d95c.gif)

*Reference: OSX 10.10.4 (14E46), Safari 8.0.7 (10600.7.12)*

**Comment by Joshfindit** [comment]
Tested on a fresh install of 10.11 Beta (15A225f) and Safari 9.0 (11601.1.39.0.2):

Same issue.

**Comment by johnotander** [comment]
Hey, thanks for reporting! I've been digging into this and think that I've been able to isolate the problem. Apparently, Safari doesn't play nice with media queries that use `rem` units. So, I'm hoping to be able to deploy a fix shortly.

**Comment by nonadmin** [comment]
I see the same thing happen in Chrome (and Safari) on the iPad.  I assume because they both use the same rendering engine?

**Comment by johnotander** [comment]
I believe so. They're all webkit based, which seems to be were the bug exists. I'll be pushing out a fix momentarily.
