### ISSUE TITLE
Highlighting options

### ISSUE THREAD

**Issue by banesto** [johnotander/pixyll#195]
What is being used for code highlighting and how can I get additional styles for at least html, javascript, coffeescript, bash & sql?

**Comment by claman** [comment]
It looks like it's _code.scss for the code, or gists

**Comment by banesto** [comment]
Yes, but it's incomplete as `javascript`, `html` and others are not being highlighted. I've added [these selectors](https://gist.github.com/nicolashery/5765395) to `_syntax-highlighting.scss` with some changed colors [and it's fine now](http://banesto.github.io/2015/08/21/serializing-form-inputs.html), but I think support for various languages should be ready out of the box.

**Comment by johnotander** [comment]
> It looks like it's _code.scss for the code, or gists

:+1: 

> I think support for various languages should be ready out of the box.

Agreed. When porting the [basscss](http://basscss.com) code highlighting selectors from hljs to pygments, it looks like I missed a large amount of classes. Whoops!

> If maintainers see it as a good addition, I could create a merge request.

I'd definitely accept a PR, though I'd prefer to continue with the current color styling rather than solarized colors.

**Comment by banesto** [comment]
Ok, then it's better you fix it then :)

**Comment by johnotander** [comment]
Sounds good, I'll get an update released tomorrow. Thanks for reporting this!

**Comment by banesto** [comment]
:+1: Great!
