### ISSUE TITLE
h1 header size specified in _variables.scss overridden by _media-queries.scss

### ISSUE THREAD

**Issue by bennettrogers** [johnotander/pixyll#196]
Specifying a different `h1` header size in `_variables.scss` only takes effect on small screen sizes. For any screen widths over 32em (`$viewport-small`) the `2.998rem` size in `_media-queries.scss` is used. (Perhaps this is intentional, but it means that the `h1` size is the only one that needs to be set in multiple locations.)

**Comment by johnotander** [comment]
Thanks for pointing this out, it's definitely a bug. It should be using the variable.
