### ISSUE TITLE
Strip HTML tags when computing reading time

### ISSUE THREAD

**Issue by AliSoftware** [johnotander/pixyll#200]
In [_layouts/post.html](https://github.com/johnotander/pixyll/blob/master/_layouts/post.html):

```diff
- {% assign minutes = content | number_of_words | divided_by: 180 %}
+ {% assign minutes = content | strip_html | number_of_words | divided_by: 180 %}
```

This way HTML formatting, URLs in anchors and all won't affect reading time.

(Sorry for not making a PR, I'm on my iPad rn)

**Comment by johnotander** [comment]
Closed via #201.
