### ISSUE TITLE
Contact forms doesn't work

### ISSUE THREAD

**Issue by naman** [johnotander/pixyll#202]
While trying out https://naman.github.io/contact/, I was redirected to https://forms.brace.io/<EMAIL>. Clearly, the service forms.brace.io is shut down. I would suggest that you remove it from the theme!

**Comment by tgaeta** [comment]
@naman when was the last time you fetched? I just pulled this repo and it comes with formspree.io's form.

**Comment by naman** [comment]
I just used tinypress setup to setup the static pages. Is there a way where
I can sync it with this repo?

**Comment by naman** [comment]
Just saw that tinypress forked your code. Maybe they can sync with your
repo, and make the necessary changes.

**Comment by johnotander** [comment]
> I just used tinypress setup to setup the static pages. Is there a way where I can sync it with this repo?

I'm not sure how tinypressco does things, so I dunno?

> Maybe they can sync with your repo, and make the necessary changes.

cc/ @tinypressco
