### ISSUE TITLE
Drop down menus

### ISSUE THREAD

**Issue by Chris1221** [johnotander/pixyll#210]
Hi everyone.

Is there a way to create sub-categories from the nav bar at the top? For example, a mouseover of "About" would roll out to show a handful of options. 

Thank you.

**Comment by johnotander** [comment]
@Chris1221 It is indeed possible with CSS, though you will need to manually add it. I recommend [this approach](http://csswizardry.com/2011/02/creating-a-pure-css-dropdown-menu/).

**Comment by Chris1221** [comment]
Thanks @johnotander, much appreciated.
