### ISSUE TITLE
Ajax Form Bug

### ISSUE THREAD

**Issue by tgaeta** [johnotander/pixyll#213]
Setting `ajaxify_contact_form: true`, the contact form on submit is being caught by the `_gotcha` action. For now, I've disabled it. Not sure why it's being caught as I have the email field filled out and the message body filled out with some text.

**Comment by Joshfindit** [comment]
I downloaded a fresh copy, enabled ajaxify, and tested by filling out email/message.
Did not see the issue you described.

Are you using an automated form-filler?
Maybe I'm missing something here; can you outline the steps necessary to reproduce what you're seeing?

**Comment by tgaeta** [comment]
I pulled the upstream, merged in the new changes, and set the Ajax to true.
The address bar whenever I hit submit would append the email and the
message along with a trailing _gotcha.

**Comment by Joshfindit** [comment]
It sounds like you may have javascript disabled, or something else interfering with the AJAX.
Can you provide a link to the page?

**Comment by johnotander** [comment]
Closing this as I haven't been able to reproduce it. Thanks for reporting!
