### ISSUE TITLE
Footnotes increase line spacing

### ISSUE THREAD

**Issue by bennettrogers** [johnotander/pixyll#220]
It seems that adding a superscript footnote (e.g. [^1]) increases the line spacing between the line with the footnote and the line above it. This looks odd in a paragraph setting since the other lines will have normal spacing.

I'm not sure what the right solution would be. Increase the spacing on all other lines to match? (That doesn't seem right). Change the margins on `vertical-align: super` elements? (Maybe the right approach).

**Comment by bennettrogers** [comment]
I added the following rule in `_sass/_typography.scss` which fixes it. I'm not sure if this is the right solution though, so I won't make a PR:

```css
sup {
    position: relative;
    vertical-align: middle;
    top: -0.9ex;
}
```

I got this solution from [here](http://bytes.com/topic/html-css/answers/97932-superscript-doesnt-distort-line-spacing#post1965414).

**Comment by johnotander** [comment]
I'd gladly accept a PR for this with an added example to the "Pixyll in Action" post.
