### ISSUE TITLE
New link underlining messed up the buttons

### ISSUE THREAD

**Issue by jtremback** [johnotander/pixyll#231]
Before I fix this, just wondering- should I modify the basecss styles, or just override them? Need to set text-shadow and background-image.

![image](https://cloud.githubusercontent.com/assets/1335122/11402334/3ea58174-934c-11e5-97d9-cabbc395da06.png)

**Comment by johnotander** [comment]
You can go ahead and override the basscss button styling if you'd like. Thanks!

**Comment by johnotander** [comment]
Closed by #232
