### ISSUE TITLE
Issue about code highlighting

### ISSUE THREAD

**Issue by creasyw** [johnotander/pixyll#238]
First of all, thank you all of the contributors of the amazing Pixyll! I have some issue with the code highlighting and have figured out a workaround, but I am not sure where exactly is wrong.

The way to reproduce the issue is:

1. Build a website with Pixyll without problem
2. [Setting it up with Github pages](https://help.github.com/articles/using-jekyll-with-pages/) and add the `Gemfile`. I would have the error `cannot load such file -- rouge`.
3. It is probably because the Github pages do not support this default highlighting package. So I switch to the `pygments` as indicated at [Jekyll doc](http://jekyllrb.com/docs/templates/#code-snippet-highlighting) (`gem install pygments.rb`, and set `highlighter` to `pygments` in config file.)
4. If I still use the `jekyll serve --watch`, I would have error `cannot load such file -- pygments`.
5. But there is no problem if I use `bundle exec jekyll serve`.

**Comment by johnotander** [comment]
Thanks for reporting, now that the Gemfile with dependencies has been added in a recent PR, I _believe_ that this should be resolved once `$ bundle install` is run. Please reopen if this isn't fixed.
