### ISSUE TITLE
Twitter sharing W3C validation error: space is not allowed

### ISSUE THREAD

**Issue by ghost** [johnotander/pixyll#239]
Hello,
W3C validator does not pass twitter sharing and gives the following error message:

Bad value for attribute href on element a: Illegal character in query: space is not allowed.
Characters should be represented in NFC and spaces should be escaped as %20.

Thank you.

**Comment by johnotander** [comment]
Thanks for reporting! I will get this fixed in the next couple days.

**Comment by johnotander** [comment]
After a bit of digging, it appears that the link should be getting constructed properly. Can you include your `_config.yml`?

**Comment by johnotander** [comment]
Looks like we need to use [`url_param_escape`](https://help.shopify.com/themes/liquid/filters/string-filters#url_param_escape) in `_includes/sharing_buttons.html`.

**Comment by tarunkxi** [comment]
Hello,
I am getting same error like:
Bad value for attribute href on element a: Illegal character in query: space is not allowed.

I have wordpress website and how to fix it.
