### ISSUE TITLE
RRSSB sharing buttons

### ISSUE THREAD

**Issue by justmytwospence** [johnotander/pixyll#256]
I personally find that the current sharing buttons are a sore thumb in an otherwise beautiful page. Would there be support for a pull request that added the [RRSSB buttons](http://kurtnoble.com/labs/rrssb/)?

**Comment by johnotander** [comment]
I'd definitely be interested in entertaining the idea. Those buttons are definitely a bit more aesthetically pleasing. My only initial worry is it looks like they don't have support for all the currently available sharing icons in Pixyll, though I'm sure we'd be able to extend it.

**Comment by johnotander** [comment]
Going to go ahead and keep the existing set for now since the current solution has a more expansive collection of icons.
