### ISSUE TITLE
Add support for "published" property of the post

### ISSUE THREAD

**Issue by Sufflavus** [johnotander/pixyll#257]
According to the Jekyll's [documentation](http://jekyllrb.com/docs/frontmatter/) there is a predefined variable "published". When I set `published: false` in the front matter block, my post is still shown on the `index.html` and `feed.xml` pages. It seems to me that unpublished posts should be hidden.
Could you please add support of this property?

**Comment by johnotander** [comment]
Definitely seems reasonable to add, I will look into supporting that this weekend.

**Comment by Sufflavus** [comment]
Thanks @johnotander, much appreciated.

**Comment by plttn** [comment]
FWIW, I'm pretty sure `published: false` was deprecated with Jekyll 3.0 (can't find anything hard on it), as both Octopress and Jekyll are now using `_drafts` folderi to mark something as unpublished.

**Comment by johnotander** [comment]
Thanks @plttn, it looks like you're indeed correct. The new Jekyll flow is using a `_drafts` directory as show in the documentation: https://jekyllrb.com/docs/drafts/

Closing since this is handled by Jekyll. 👯 ✨ ✨
