### ISSUE TITLE
Double slashes in URL when using GitHub Project setup

### ISSUE THREAD

**Issue by alxmjo** [johnotander/pixyll#259]
I followed the directions to deploy Pixyll on a GitHub project page, but when I click on the homepage link at the top of the screen I'm taken to alxmjo.github.io//code instead of alxmjo.github.io/code, as I'd expect. I've tried modifying base-url and the header.html page but nothing has worked. I'm not sure if this is a bug or my mistake, but I know that I followed the directions in the Pixyll README.md exactly. For what it's worth, the link still works. It just looks ugly.

**Comment by johnotander** [comment]
Hey @alxmjo, could you include your `_config.yml`?

**Comment by alxmjo** [comment]
Attached (as a txt file). Thanks for looking.

[_config.txt](https://github.com/johnotander/pixyll/files/95492/_config.txt)

**Comment by DainelPark** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

andmylife@naver.com 님께 보내신 메일 <Re: [pixyll] Double slashes in URL when using GitHub Project setup (#259)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람의 메일박스 용량이 가득 찼습니다.  


--------------------------------------------

**Comment by johnotander** [comment]
Sorry about the terrible delay on responding 😊 😊 😊 .

For future reference in case others come across this, the `baseurl` configuration option doesn't need a leading `/`. So it should be `foo/bar` rather than `/foo/bar`.
