### ISSUE TITLE
Add an Index, so a reader can view a list of Posts

### ISSUE THREAD

**Issue by JakeWengroff** [johnotander/pixyll#261]
It would be helpful for blog readers if Pixyll included a location where readers can view an Index of previously published posts, then click on the title to read the post.
Given the clean look and organization of Pixyll, I do not know where the Index of posts would appear.
Any thoughts or ideas would be great.
Thank you.

**Comment by DainelPark** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

andmylife@naver.com 님께 보내신 메일 <[pixyll] Add an Index, so a reader can view a list of Posts (#261)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람의 메일박스 용량이 가득 찼습니다.  


--------------------------------------------

**Comment by johnotander** [comment]
Hey @DainelPark it looks you have an email autoresponse (seen in #259, too) that's flooding this issue tracker, do you mind turning it off for Pixyll related email items? Thank you!

**Comment by DainelPark** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

andmylife@naver.com 님께 보내신 메일 <Re: [pixyll] Add an Index, so a reader can view a list of Posts (#261)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람의 메일박스 용량이 가득 찼습니다.  


--------------------------------------------

**Comment by johnotander** [comment]
Thanks for creating this issue @JakeWengroff. I'm going to opt out of adding this functionality to keep things as vanilla Jekyll as possible.

If you'd like help getting this functionality in your own custom implementation please let me know!
