### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by nazarblch** [johnotander/pixyll#262]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb 
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.0.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby2.1
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20160122-11019-1h3ncin/nokogiri-1.6.7/gems/nokogiri-1.6.7 for inspection.
Results logged to /tmp/bundler20160122-11019-1h3ncin/nokogiri-1.6.7/extensions/x86-linux/2.1.0/nokogiri-1.6.7/gem_make.out
An error occurred while installing nokogiri (1.6.7), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.7'` succeeds before bundling.

**Comment by mgrachev** [comment]
> zlib is missing; necessary for building libxml2

You need to install `zlib`

For Debian/Ubuntu:
```
sudo apt-get install zlib1g-dev liblzma-dev
```

Source: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by johnotander** [comment]
Thanks for reporting, and thanks for the added info @mgrachev! I'm closing as @mgrachev as provided the necessary info/documentation.
