### ISSUE TITLE
missing ruby requirements

### ISSUE THREAD

**Issue by walchko** [johnotander/pixyll#267]
Hello!

I am new to jekyll and installed it with `gem`, but your install directions forgot to add the gems:

* jekyll-paginate
* jekyll-sitemap

Suggest you add those to the install instructions.
Thanks!

**Comment by johnotander** [comment]
Thanks for reporting. I've updated the installation instructions to use the `bundler` gem, this should pull in all required gems. Please let me know if you encounter any more issues.
