### ISSUE TITLE
code highlighting with kramdown and rouge

### ISSUE THREAD

**Issue by mkoohafkan** [johnotander/pixyll#278]
I recently updated my site to pixyll 2.0 and updated my config file to use kramdown and rouge. Unfortunately my code blocks have lost their highlighting regardless of whether I use {% highlight %} or backticks. Are there other config settings I need to change?

**Comment by mkoohafkan** [comment]
actually, I think this was my mistake. working with the wrong branch

**Comment by mkoohafkan** [comment]
after updating my site to the current version of Pixyll, it looks like the syntax highlighting issue remains. I think it is an issue with the CSS class but I'm not sure where to modify it; basically, using kramdown with rouge results in a class `highlighter-rouge` whereas Pixyll defines the class `highlight`. Is it is as simple as renaming the `highlight` class to `highlighter-rouge`?

**Comment by mkoohafkan** [comment]
alright, further investigation shows that things are working as intended---rouge just doesn't do nearly as good a job...

**Comment by johnotander** [comment]
My apologies, I must've missed this. Glad you were able to figure it out!
