### ISSUE TITLE
Font of .fa class does not scale

### ISSUE THREAD

**Issue by Calavoow** [johnotander/pixyll#290]
The font size of text links with the Fontawesome class (`.fa`) do not scale with the rest of the text.
Given the markdown

```markdown
To contribute go to [ Calavoow](https://github.com/calavoow){: .fa .fa-github}/
[quasci.com](https://github.com/Calavoow/quasci.com/) and submit a pull request. Or send me an email.
```

The resulting text of the ` calavoow` text is too small on large layouts. You can see it [here](http://quasci.com/about/). It looks like some CSS conflict between the `fa` class and the normal text class.

Tested on Firefox 47.0.1.

**Comment by plttn** [comment]
I'm not 100% sure, but it looks like this might be something you can't easily fix. If you look at the CSS chain for that, the entire `<a>` is getting the `fa` class. For FA icons to work, it has to change the font to the fontawesome font.

There's no way to change the rest of the `<a>` back to the standard font family.

**Comment by Calavoow** [comment]
Thanks for your reply. As it turns out it's recommended to use an empty `<i>` as container for the fontawesome content (see their examples). This turns out just fine.
