### ISSUE TITLE
how can i add image to summary

### ISSUE THREAD

**Issue by SchwiftyLife** [johnotander/pixyll#298]
i like to have an image in the summary but i'm unable to achieve that.
how can i do it?
thanks

**Comment by SchwiftyLife** [comment]
okay i managed to do that by adding 
`<p class="post-image">
            {% if post.image %}
              <img src="{{ site.baseurl }}/images/{{ post.image }}">
            {% else %}
              {{  }}
            {% endif %}
          </p>`
to index html and defining an image variable under summary in my posts like this :
`layout:     post
title:      Pixyll in Action
date:       2014-06-10 12:31:19
summary:    See what the different elements looks like. Your markdown has never looked better. I promise.!
image: me.jpeg
categories: jekyll pixyll`

**Comment by alexpanov** [comment]
@SchwiftyLife thank you! This is exactly what I was looking for.
