### ISSUE TITLE
disqus set up on gh-pages project site

### ISSUE THREAD

**Issue by aidanreilly** [johnotander/pixyll#312]
hi, having trouble setting up disqus. i think i've done everything on the disqus side, but wondering is there something obvious I'm missing on the jekyll/site side? is all that needs to be done add a disqus shortname to _config.yml?

https://github.com/aidanreilly/man_synth/tree/gh-pages

thanks!

**Comment by bartekpl** [comment]
Hi,
from what I've seen, the Disqus short name in _config.yml on your repo is different than what it is on your website (got the domain from CNAME file). Is this correct?

**Comment by aidanreilly** [comment]
thank you - all sorted now. it was an mis-match between the cname value and what i had in disqus.
