### ISSUE TITLE
RFE: Producing anchor tags for section/title headers

### ISSUE THREAD

**Issue by mmoayyed** [johnotander/pixyll#339]
Certain github wikis and documents produce visual anchor tags for h1,h2,h3 tags and such.

Example:
https://apereo.github.io/cas/development/#getting-started

Could this be something that can be handled automatically by this theme?

**Comment by ashawley** [comment]
The theme uses Font Awesome, so it seems like it should be possible.

http://fontawesome.io/icon/link/

Here was a post about doing this in Jekyll from a few years ago.  Not sure if would work here with this theme, or not.

http://ben.balter.com/2014/03/13/pages-anchor-links/

**Comment by mmoayyed** [comment]
Thanks very much! I shall experiment.

**Comment by plttn** [comment]
I use [anchorjs](https://github.com/bryanbraun/anchorjs) to do this. Example [here](https://plttn.me/octopress/jekyll/2015/01/17/yet-another-octopress-2-dot-0-plus-travis-ci-guide/).

**Comment by mmoayyed** [comment]
That is beautiful. Awesome work! I may simply borrow your approach and get going. I shall post back once I have the example ready. 

Thanks again .

**Comment by mmoayyed** [comment]
Another example in case someone needs to see/use: https://apereo.github.io/

**Comment by ashawley** [comment]
Anchorjs is actually part of pixyll, see the [documentation](https://github.com/johnotander/pixyll#anchorjs)

**Comment by mmoayyed** [comment]
Thanks. Sounds like I added the lib as a duplicate then. I'll see if I can simply use it per the docs. Thanks for the reference.
