### ISSUE TITLE
Ugly anchors in headers

### ISSUE THREAD

**Issue by eonist** [johnotander/pixyll#344]
I love pixyll. But lately iv'e discovered some ugly anchors creeping in to the otherwise elegant layout. Any thoughts? 

<img width="973" alt="screen shot 2017-07-12 at 15 31 43" src="https://user-images.githubusercontent.com/11816788/28120060-40fec30e-6717-11e7-9d28-33712d41ced0.png">

**Comment by bartekpl** [comment]
You have something wrong in your CSS (I think). Overall, this feature is documented [here](https://github.com/johnotander/pixyll#anchorjs). I'm using it on my blog - makes Pixyll even more elegant ;).

**Comment by eonist** [comment]
My config.yml file has it set to disbaled: 

```
enable_anchorjs: false
```

but still shows up 😭


How does one get rid of it?

**Comment by ashawley** [comment]
Is your web site public?  Is your git repo public?  Can you share them?

**Comment by eonist** [comment]
https://github.com/eonist/eonist.github.io  http://eon.codes/

**Comment by ashawley** [comment]
Maybe it started happening after this was added?

https://github.com/eonist/eonist.github.io/commit/dee23126bae7aea52178364f3cfca05670d611f1#diff-e921a390257abd15c1742300f2417b13R62

**Comment by eonist** [comment]
@ashawley You have a good eye for finding errors. I removed this part: 

```
<script><!--adds header linking functionality-->
        $(function() {
          return $("h2, h3, h4, h5, h6").each(function(i, el) {
            var $el, icon, id;
            $el = $(el);
            id = $el.attr('id');
            icon = '<i class="fa fa-link"></i>';
            if (id) {
              return $el.prepend($("<a />").addClass("header-link").attr("href", "#" + id).html(icon));
            }
          });
        });
    </script>
```

And it worked. It probably came along after i forked the latest pixyll and then copied over my custom includes from an old pixyll. I might also have messed around with anchor tags at one point ¯\_(ツ)_/¯  Thx a bunch anyways. Really appreciate it 😃

**Comment by ashawley** [comment]
Glad we figured it out! 😄  Otherwise, that was going to be really confusing!
