### ISSUE TITLE
Odd Mathjax Styling

### ISSUE THREAD

**Issue by avery-laird** [johnotander/pixyll#357]
After merging with the latest branch, I'm seeing some odd mathjax formatting:

![image](https://user-images.githubusercontent.com/987308/33516157-c1aa2abe-d7a8-11e7-81fa-8d4ec5b15644.png)

From the image, you can see the math is blue, and also bolded more than it should be (especially for the inline math). I do have some custom styles, but they're very minimal:
```
blockquote {
	margin-left: 0rem;
	padding-bottom: 0rem;
	padding-top: 0rem;
}

blockquote p {
	font-size: 0.9rem;
}

div.footnotes > ol > li > p, div.footnotes > ol {
	font-size: 0.8rem;
}

a > code {
	color: #0076df;
}

#mc_embed_signup {
	background: inherit !important;
	font: inherit !important;
}

.highlight, .highlight .p {

	font-size: 0.8rem;
}
```

I suspected my style for links might have something to do with it, so I temporarily removed them, but the issues remains. According to my inspector, it's a defined style in `pixyll.css`:

![image](https://user-images.githubusercontent.com/987308/33516196-6c024e88-d7a9-11e7-8036-2637c7c06f6e.png)

You can also see in the image that for some classes the colour changes, but for others it remains the inherited body text colour. If I ignore the styles for both the `mo` and `mi` classes (removing the colour and bolding) it seems to render fine. However, I'm not sure why this style would exist, and I'm hesitant to change anything without fully understanding what's going wrong here. Any suggestions?

**Comment by ashawley** [comment]
The last significant change to Mathjax was #338.  Does git bisect confirm that?

**Comment by avery-laird** [comment]
Thanks for your reply, I just isolated the issue to one of my own stylesheets (a pygment stylesheet). Line 32 in `pixyll.css` is actually an import statement for that sheet. It looks like the classes for pygments and mathjax intersect with `mo` and `mi`. This obviously isn't an issue related to pixyll, so I'll close the issue
