### ISSUE TITLE
Navigation pages in HTTPS

### ISSUE THREAD

**Issue by christopherkade** [johnotander/pixyll#358]
First off thank you for your work !

My blog is hosted on the following subdomain of my website: https://blog.christopherkade.com, when I navigate to a second page, it uses HTTP and not HTTPS. Why is that?

If I understand correctly, you handle pagination in the following lines:

```html
{% if paginator.next_page %}
      <a class="pagination-item" href="{{ paginator.next_page_path }}">{{ site.text.pagination.older }}</a>
{% else %}
      <span class="pagination-item disabled">{{ site.text.pagination.older }}</span>
{% endif %}
```

Note that my config's `blogurl` is `https://blog.christopherkade.com`.

Thank you in advance.

**Comment by ashawley** [comment]
Looks like you need to contact your hosting service.  Pixyll appears to be doing the right thing.  The redirect is server-side:

```
$ curl -I https://blog.christopherkade.com/page2
HTTP/1.1 301 Moved Permanently
Date: Sun, 24 Dec 2017 19:44:48 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d53d884010b9e170f6dac076c61ca08341514144688; expires=Mon, 24-Dec-18 19:44:48 GMT; path=/; domain=.christopherkade.com; HttpOnly
Location: http://blog.christopherkade.com/page2/
Access-Control-Allow-Origin: *
Expires: Sun, 24 Dec 2017 19:54:48 GMT
Cache-Control: max-age=600
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 0
X-Served-By: cache-jfk8138-JFK
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1514144689.577321,VS0,VE11
Vary: Accept-Encoding
X-Fastly-Request-ID: 06e5b5f9e41da5a5a40650d46dcdfb69213e3555
Server: cloudflare
CF-RAY: 3d260eaf08fc924e-EWR
```

**Comment by christopherkade** [comment]
Thanks for the heads up, it was a problem on my side, I changed a redirection rule and all seems perfect now.

**Comment by ashawley** [comment]
Cool, I'm glad you were able to resolve it.

What is the significance of `blogurl`?  I'm not seeing a reference to it in pixyll.  Is it something elsewhere in jekyll?

**Comment by christopherkade** [comment]
I added it a while back to tweak Pixyll (and forgot, hence the mention).
