### ISSUE TITLE
Multiple Authors

### ISSUE THREAD

**Issue by nahtnam** [johnotander/pixyll#89]
Hey!

Feature Request:
Would it be possible to have multi-author support? If so, when?

**Comment by johnotander** [comment]
Sorry about letting this fall through the cracks, @nahtnam. It's been a few months :(. After more deliberation, I think I will avoid adding in multiple authors as it will add a bit more complexity and won't be a standard use case that I'm aware of.

However, if I get some time, I might create a fork for a `pixyll-multi-user` theme.

**Comment by nahtnam** [comment]
Oh ok. Thanks for the update/reply!

**Comment by Calavoow** [comment]
@johnotander Could we add support for multiple authors on the post level? Maybe add a field to the post template so that when authors are specified in a post's front matter the authors show up?
